### ISSUE TITLE
`MathSenderGTestBase` and `MathSenderTesterBase` missing from `build-fprime-automatic-native-ut/Components/MathSender`

### ISSUE THREAD

**Issue by capsulecorplab** [fprime-community/fprime-tutorial-math-component#12]
`MathSenderGTestBase` and `MathSenderTesterBase` directories not being generated as per [(Optional) Inspect the generated code
](https://fprime-community.github.io/fprime-tutorial-math-component/docs/writing-unit-tests-1.html#optional-inspect-the-generated-code)

**Comment by thomas-bc** [comment]
Fixed with v3.4.0
