### ISSUE TITLE
fprime-util build fails in MathReceiver because of case mismatch

### ISSUE THREAD

**Issue by hukuzatuna** [fprime-community/fprime-tutorial-math-component#36]
In the provided example in MathReceiver.cpp, the operators are listed as ADD, SUB, MUL, and DIV.  But in ../../Types/MathTypes.fpp they are listed as Add, Sub, Mul, and Div. This causes a compiler failure on fprime-util build in MathReceiver.

Fix is to make them all upper, or all mixed. 

Thanks!

**Comment by thomas-bc** [comment]
@hukuzatuna could you point me to where you are seeing Add/Sub/etc. ?

I see them capitalized everywhere

https://github.com/fprime-community/fprime-tutorial-math-component/blob/bfd4c5706f9279062e4c0b1f89db4e2bde8d8692/Types/MathTypes.fpp#L4-L9

https://github.com/fprime-community/fprime-tutorial-math-component/blob/bfd4c5706f9279062e4c0b1f89db4e2bde8d8692/Components/MathReceiver/MathReceiver.cpp#L47-L56

And in the docs: https://github.com/fprime-community/fprime-tutorial-math-component/blob/main/docs/defining-types.md#implementing-the-types

**Comment by thomas-bc** [comment]
No worries!
